### ISSUE TITLE
Let a User Save Personal Favorites, or See Global Favorites

### ISSUE THREAD

**Issue by KeeganW** [KeeganW/ti4#16]
Add a page that lets people share or use their personal or global favorites. Either full map, or map generation settings.

**Comment by KeeganW** [comment]
Personal favorites could be saved in a cookie.

If this is to be truly a global favorites option, it would need to gather some type of "favorite" from the user who wants to save their personal favorites. Then there would need to be an up/down kind of voting on it. TBH I think the second part is out of scope of this project. Saving personal favorites to a cookie seems reasonable so that they can restore to a previously create set of maps/setting (without just copying the url).

**Comment by philihp** [comment]
I feel like a good way of doing this would be to have App.js use React Router to keep vars inside the URL. Then people could share map settings around since it's deterministic with the seed. Browser bookmarks can then be used to save personal favorites. Up/down voting means there needs to be some sort of mutable data store, somewhere.

**Comment by KeeganW** [comment]
@philihp Agreed with your points. The deterministic portion has been added. For example, [this map](https://keeganw.github.io/ti4/?settings=T31002570FFF) will always generate a 3 player map with Hope's End in the bottom right corner below P1. If you played with the same players all the time, you could bookmark a page like [this](https://keeganw.github.io/ti4/?settings=T60003174FFT|KeeganW|philihp|Billy|Bob|Brock|Bro|Bart|Brian), which stores the player names of your friends.

Using github pages it doesn't make sense to have the a data store, because that would have to be hosted somewhere else (since github only allows for static pages). I think having some sort of "Submit this map for review as a new preset" button in the sharing popup would be more realistic, and then I could gather and review maps, then add them as presets (as part of #27).

Closing for now, as I think this feature is available already, or is part of other tickets.
