### ISSUE TITLE
Add a TTS Button to Copy the Tile List To The Clipboard to Paste Into TTS

### ISSUE THREAD

**Issue by KeeganW** [KeeganW/ti4#40]
Use an icon of tabletop simulator, or a copy icon. Will need to format the list to match the exact format (so the empty tiles (-1's) need to be converted to 0's).

**Comment by darrellanderson** [comment]
This is awesome.  How stable are your form fields and option values?  There could be a small control panel inside TTS that "submits" your form to load the map string directly.  (Edit: sorry, ignore this comment -- browsing the source shows this is all in-browser javascript and not a server-side component TTS could call.)

**Comment by KeeganW** [comment]
@darrellanderson While it is in browser, it wouldn't be too hard to pull the tile string generation functionality out and into an endpoint that could be called by TTS. I haven't worked too much with TTS, but all it would need would be an POST request API endpoint that gathers a few fields, and would return a tile string right? That could certainly be created and exposed.

**Comment by KeeganW** [comment]
Completed with 8988b2827
