### ISSUE TITLE
Red systems next to eachother

### ISSUE THREAD

**Issue by fjulle** [KeeganW/ti4#50]
Thanks for a nice map generator 🙂

Standard rules for maps are: No red systems next to one another.

The mapmaker puts them next to each other alot of the time.

Ive read your post about it, but if i rearrange the tiles. Ill be partisan to the decision, and the map will not be have as strong a claim to neutrality.

**Comment by KeeganW** [comment]
This seems to be happening mostly with the PoK setting turned on. There were not many blank tiles being used (from using old `tileData` names) but there is still an issue of it happening often. Any anomaly that cannot be moved should probably just be replaced with a blank tile.

**Comment by KeeganW** [comment]
@fjulle I found a bug with which tiles were being added to the board (not enough blank tiles) and I fixed the tiles being put next to one another (they get replaced with blank spaces now). There may be an edge case with the PoK alpha wormhole tile (its an astroid field anomaly as well), but I haven't seen it happen quite yet.

**Comment by fjulle** [comment]
Hey

Wow nice :) ill check it out! Thanks!

*Venlig Hilsen*
*Ulrik Vang Hansen*
*Lektor, Filosofi & Samfundsfag, HF & VUC Fyn*
