### ISSUE TITLE
No Legendary Planets in 6p Maps

### ISSUE THREAD

**Issue by CurropepeMix** [KeeganW/ti4#51]
In balanced 6p Maps with PoK expansion, legendary planetes Hope's End and Primor never show up.

**Comment by KeeganW** [comment]
This has to do with the weighting that is happening. I will be making 2 changes to help with this though. 
1. Adding an include/exclude list which forces certain tiles to be included or excluded on generation.
2. Randomly pre-picking tiles, then weight scoring them, then placing them on the map. Right now it is just weight scoring them and placing them, resulting in the same planets being used constantly.

**Comment by KeeganW** [comment]
Legendary tiles are now appearing (fixed in 5f9d273) in all maps when using PoK expansion. Include and exclude lists are being tracked in #49.
