### ISSUE TITLE
Hyperlane Adjacency

### ISSUE THREAD

**Issue by Conro101** [KeeganW/ti4#60]
When looking at the information about systems adjacent to players' home systems, tiles that are technically adjacent due to hyperlanes aren't accounted for.

**Comment by KeeganW** [comment]
Definitely a bug, thanks for pointing this out @Conro101!

**Comment by Conro101** [comment]
Also, just a quick question: does the algorithm take into consideration the legendary planet abilities you get from controlling those planets when balancing the planet placements?

**Comment by KeeganW** [comment]
It does not, it is purely based on resource on the tile. That is an interesting point though, and might be worth an additional toggle slider for the custom system weighting. 

My only worry is that while it will increase the tile value, that will actually end up putting the legendary planet tiles in bad spots. I imagine people probably won't be happy with a legendary planet being in front of one player, and would prefer it to be between at least two players, but more likely closer to the middle of the board. I think this is where locking a tile is most useful, to keep the legendary planets locked to the middle of the board.

**Comment by Conro101** [comment]
I think putting it in the middle is better, the reason I asked was because I saw it generate with both Hope's End and Primor directly next to one home system, since they're actually not that huge resource-wise. I'll definitely remember to lock them next time!

**Comment by KeeganW** [comment]
@Conro101 The more info count on hyperlanes should be fixed now. You can see that on a map [like this](https://keeganw.github.io/ti4/?settings=T81008379FFF) where player 7 has the appropriate resources and tech bonuses assigned to their total.
