### ISSUE TITLE
Asset Summary with Custom Player Labels [PoK]

### ISSUE THREAD

**Issue by Theo85** [KeeganW/ti4#62]
Issue:
Last player stats missing in Assets Adjacent to Home System view

How to replicate:
Use Prophecy of Kings and custom labels for player names, using Assets Adjacent to Home System view. Chances to replicate is I would say 20% (just generate again if needed). Tried to replicate it without PoK or without player labels but were not able.

**Comment by Theo85** [comment]
BTW the app is excellent!!!

**Comment by KeeganW** [comment]
Thanks! I was able to replicate this bug, it is definitely an issue (and very strange behavior). It looks like it is only happening after the PoK toggle is triggered (but does require names to be specified). When copying a url, and then pasting it in a new window, this bug does not appear (despite many additional generations). Changing the names doesn't appear to affect the bug, but there does need to be names specified for it to happen. It is possible that this has to do with parsing a url string as well. Locking a tile next to the last player's home system does not affect this bug.

**Comment by Theo85** [comment]
Tried to look at the code but JS is not my thing :)

**Comment by qbixsd** [comment]
MoreInfo.js, line 71, change <58 to <=58 ;-)

**Comment by qbixsd** [comment]
I've doublechecked the issue, why when you go from URL you don't have the issue. It seems, that homeworld generation does not take into account the PoK setting when loaded from URL. I've created another issue for that: https://github.com/KeeganW/ti4/issues/65

**Comment by KeeganW** [comment]
Looks like #75 fixed this as well, I cannot reproduce this anymore.
