### ISSUE TITLE
Discord integration?

### ISSUE THREAD

**Issue by PhilRoi** [KeeganW/ti4#67]
Your Generator has become popular on the big discord for playing TI4 on TTS.  Reach out to me if you ever want to have a channel specifically for your generator on it  or might be intrested in working with some other devs I know to possibly do some collaborative work.   I know of 3-4 map gens and utilities around the web that each have distinctly cool features that it might be feasible to integrate into a single project.

I run the discord, so easy enough to set-up.   We also have toyed around with the possibility of developing a map generating utility/tool that is usable from within the TTS Mod we use to play TI4.    @philroi if that means anything to you :)

**Comment by PhilRoi** [comment]
the map string format we use for the mod does go through occaisional changes as well, so integration would help you to keep your tool compatible with the changes.

**Comment by KeeganW** [comment]
I've reached out via discord. I'd be happy to have a channel for the generator, as I'm betting I would get a lot of feedback through there (and could push change logs and things).

For features let me know what the cool features you think others have that this generator does not. I am all for implementing cool features.

Are you using a different mod than [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=1466689117)? If so (and its more updated) I would be happy to change the string to match whatever changes you make (or suggest some changes, for things like hyperlane rotations). Just let me know on that front what you were thinking specifically. 

I have another issue #44 which would be an endpoint to reach out to from inside the mod, which could spit out specifically generated tile strings (and avoid the UI of this project) which could be helpful for the TTS mod specifically.

**Comment by KeeganW** [comment]
Connected with the discord development team and implemented some changes already. The remaining integration is tracked by #44.
