### ISSUE TITLE
Assets adjacent to home incorrect

### ISSUE THREAD

**Issue by cmcooling** [KeeganW/ti4#78]
In the four-player map I generated https://keeganw.github.io/ti4/?settings=T40008068FFF (image attached) it appears that the tech specialties for the top player (who I believe is P4) have not been calculated correctly in the "Assests Adjacent to Home" tab. It appears that the yellow tech-spec of Wellon has not been included, even though the resources, influence and planet traits have been.

It also appears one of the industrial traits for P2 (who I believe is the bottom player) has not been included in their summary.

As a side note, it might be convenient to have the four player positions marked "P1", "P2", etc to make it easy to see which of the positions is referenced by each player number. 

![Map maker bug](https://user-images.githubusercontent.com/12444767/105153870-da911180-5b00-11eb-9be1-1c7ec2630d0c.png)

**Comment by cmcooling** [comment]
Oops, scratch the part about P2 having the wrong planet traits, that was my eyes being dumb.

**Comment by KeeganW** [comment]
@coolernato It appears I was missing the cybernetic trait for Wellon... good catch!

As a side note, you can see the player names with the tile number overlay turned on. I think you have a good point though, and that the player names should show up when the adjacent info panel is open... I will make a new feature issue for that.
