### ISSUE TITLE
5pl maps never have 10 red tiles with setting Warp

### ISSUE THREAD

**Issue by p2812** [KeeganW/ti4#87]
All is in the title.
Thanks for this tool !

**Comment by p2812** [comment]
It's seem to be because all wormholes are counted as red tiles, when ones with planets shouldn't.

**Comment by p2812** [comment]
I'm sorry but I don't understand, I just tried and this is absolutely not fixed ?

**Comment by KeeganW** [comment]
While the change has been made in the code, it hasn’t been uploaded to the website yet. I will try to deploy this weekend and post a comment once I have. Sorry for the confusion!

**Comment by KeeganW** [comment]
@p2812 This should be deployed now. See this [example](https://keeganw.github.io/ti4/?settings=T51004039FFTT030423222120), I count 10.

**Comment by p2812** [comment]
Indeed, good job, thanks a lot !

**Comment by p2812** [comment]
If you ever come to Lyon, France, warn me : maybe we could play ;)
