### ISSUE TITLE
Naalu & Nekro home system tile is blank (ST_-1.png)

### ISSUE THREAD

**Issue by ragwy64** [KeeganW/ti4#90]
The issue and can be fixed changing the regexp in file App.js (line 577) from:
/^([0-7][0-9]?|80|81|82|-1)-?([0-5])?$/gm 
to:
/^([0-9][0-9]?|80|81|82|-1)-?([0-5])?$/gm

**Comment by KeeganW** [comment]
Closed with #89 , thank you @tomb1125. Example [here](https://keeganw.github.io/ti4/?settings=T51005196FFTT0304231011).
