### ISSUE TITLE
balance algorithm OR map from string

### ISSUE THREAD

**Issue by kwladyka** [KeeganW/ti4#94]
It will be great to able able to load `79 60 50 31 21 73 40 62 37 41 66 64 23 25 26 77 33 38 0 72 76 0 63 39 0 35 27 0 44 20 0 30 46 0 65 32`.

Why?

https://keeganw.github.io/ti4 unfortunately is very unbalanced. It seems to https://joepinion.github.io/ti4-map-lab/ doing this better, but visual representation is terrible. So on the end I would like to generate random map here https://joepinion.github.io/ti4-map-lab/ and see it on https://keeganw.github.io/ti4.

Or just add better balance for https://keeganw.github.io/ti4 will be even better.

PS great work

**Comment by KeeganW** [comment]
Hey @kwladyka! Thank you for the suggestion. While I do plan on improving the generation, I have now added a way to import tile strings in the format you mentioned! 

You can use this with the import button:
<img width="54" alt="Screenshot 2023-01-12 at 7 34 01 PM" src="https://user-images.githubusercontent.com/7226822/212231200-9b91be45-7930-4e46-af56-a8bbd40e14f9.png"> 
and then pasting your above string, and clicking the `Load Map` button, which should load the map with the string you entered!
