### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by Snakeye69** [KeeganW/ti4#95]
Hi,

I wonder if you could help me. I am a huge fan of Twilight Emperium IV (inc the expansion).

I had an idea of creating wooden disks with stickers to represent the planets of systems and place them on the map. During setup, the disks would be placed on the respective hexes and when a player takes over a planet, he will pick up the disk off the hex tile as oppossed to trying to find the card; the disk would contain all the info of the planet, minus flavour txt.

I was wondering if you could share the graphics you have of the hexes/planets so I can incorporate them on the disk design. This will save me an awful long time from scanning the images from the cards. This is ofc for personal use, as I am not looking to profit from this.

I understand if the answer to this is no due to IP, but thought to ask in any case.

Thank you in advance,

George

**Comment by KeeganW** [comment]
Hey @Snakeye69

You can find all the images in the [public folder](https://github.com/KeeganW/ti4/tree/master/public/tiles). However if you are looking for tokens and icons there are other sources like [this one](https://boardgamegeek.com/filepage/180049/ti4-race-and-tech-symbols-vectorized).

Hope that helps!

**Comment by dotlogix** [comment]
Hey @Snakeye69 I just opened this one here https://github.com/KeeganW/ti4/issues/96
If you are interested let me know.

**Comment by KeeganW** [comment]
Full scans provided by @dotlogix are helpful, I will let them handle requests for the links, but they can also be found [here](https://www.reddit.com/r/twilightimperium/comments/qpklar/i_need_help_finding_good_quality_images_of_ti4pok/htsk2yx/).
