### ISSUE TITLE
Offer to provide denoised images

### ISSUE THREAD

**Issue by dotlogix** [KeeganW/ti4#96]
Hey there, I did a whole rescan of the system tiles and would offer you to use them if you like.
Did a whole lot of work for denoising and removing the moire and checkered pattern from the tiles.
They look pretty nice I would say :D
https://drive.google.com/file/d/1ttRRcZvnnsuUZqQh3Bxkk0ytA9b4Y31D/view?usp=sharing

If you are interested let me know so I can create a PR or send you a link.

**Comment by Snakeye69** [comment]
This is awesome! Thank you very much! Would appreciate the scans!

**Comment by dotlogix** [comment]
Please see the PR above :)
![before](https://user-images.githubusercontent.com/16420200/150659304-a1125683-f9af-4dab-8bb5-83856568cb55.png)
![after](https://user-images.githubusercontent.com/16420200/150659306-a54d54a0-43a9-41a7-a1ed-2e037393cedc.png)

**Comment by dotlogix** [comment]
@Snakeye69 if you want the originals with higher resolution (2k) send me a message in discord secrest#6082

**Comment by Snakeye69** [comment]
I tried sending you on Discord but the msg didnt go through due to not being friends or have commond server. I would love the original 2K scans.
